from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA

import gradio as gr

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
def get_llm():
    model_id = 'mistralai/mixtral-8x7b-instruct-v01'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,
        GenParams.TEMPERATURE: 0.5,
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )
    return watsonx_llm

## Document loader
def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document

def show_pdf_content(file):
    loader = PyPDFLoader(file.name)
    documents = loader.load()
    # Se for multipáginas, pode juntar todos, ou só mostrar a primeira página:
    content = documents[0].page_content[:1000]
    return content

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

# --- Tarefa 3: Embedding de uma frase ---
def embed_query_interface(query):
    embedding_model = watsonx_embedding()
    embedding = embedding_model.embed_query(query)
    if isinstance(embedding, list):
        return f"Embedding (primeiros 5 valores):\n{embedding[:5]}"
    return str(embedding)

## Vector db
def vector_database(chunks):
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

## Embedding model
def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True},
    }
    watsonx_embedding = WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr",
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=embed_params,
    )
    return watsonx_embedding

## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever

## QA Chain
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']


def split_text_content(text):
    from langchain.schema import Document
    doc = Document(page_content=text)
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50
    )
    chunks = splitter.split_documents([doc])
    result = ""
    for i, chunk in enumerate(chunks):
        result += f"Chunk {i+1}:\n{chunk.page_content}\n{'='*30}\n"
    return result

# Exemplo LaTeX para testar na interface
latex_text = """
\\documentclass{article}

\\begin{document}

\\maketitle

\\section{Introduction}

os Modelos de linguagem grande (LLMs) são um tipo de modelo de aprendizado de máquina que pode ser treinado em grandes quantidades de dados de texto para gerar linguagem semelhante à humana. Nos últimos anos, os LLMs fizeram avanços significativos em várias tarefas de Processamento de linguagem natural (NLP), incluindo tradução de idiomas, geração de texto e análise de sentimentos.

\\subseção{História dos LLMs}

Os primeiros LLMs foram desenvolvidos nas décadas de 1980 e 1990, mas eram limitados pela quantidade de dados que podiam ser processados e pelo poder computacional disponível na época. Na última década, no entanto, os avanços em hardware e software tornaram possível treinar LLMs em conjuntos de dados maciços, o que levou a melhorias significativas no desempenho.

\\subseção{Aplicações de LLMs}

Os LLMs têm muitas aplicações no setor, incluindo chatbots, criação de conteúdo e assistentes virtuais. Eles também podem ser usados no meio acadêmico para pesquisas em linguística, psicologia e linguística computacional.

\\end{document}
"""

#tarefa 4
def vectordb_search_interface(query):
    from langchain_community.document_loaders import TextLoader

    # Carrega e faz split do TXT
    loader = TextLoader("new-Policies.txt")
    documents = loader.load()
    splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks = splitter.split_documents(documents)

    # Cria DB vetorial
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)

    # Faz a busca
    results = vectordb.similarity_search(query, k=5)
    saida = ""
    for i, doc in enumerate(results):
        saida += f"Resultado {i+1}:\n{doc.page_content}\n{'='*30}\n"
    return saida


# --- Tarefa 5: Retriever Demo com ChromaDB (2 resultados) ---
def chroma_retriever_interface(query):
    from langchain_community.document_loaders import TextLoader

    # Carrega e divide o documento
    loader = TextLoader("new-Policies.txt")
    documents = loader.load()
    splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks = splitter.split_documents(documents)

    # Cria o embedding model e banco vetorial
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)

    # Usa o retriever do Chroma para busca (k=2)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    results = retriever.get_relevant_documents(query)
    saida = ""
    for i, doc in enumerate(results):
        saida += f"Resultado {i+1}:\n{doc.page_content}\n{'='*30}\n"
    return saida

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="RAG Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)
# Launch the app
rag_application.launch(server_name="0.0.0.0", server_port= 5055)

#rag_application =gr.Interface(
#    fn=show_pdf_content,
#    inputs=gr.File(label="Upload PDF File"),
#    outputs=gr.Textbox(label="Primeiros 1000 caracteres"),
#    title="Preview do PDF",
#    description="Faça upload de um PDF e veja os primeiros 1000 caracteres"
#).launch(server_port=5056)

# 2: Interface Gradio para dividir texto (inclusive LaTeX)
#splitter_app = gr.Interface(
#    fn=split_text_content,
#    inputs=gr.Textbox(label="Coloque aqui o texto a ser dividido", value=latex_text, lines=20),
#    outputs=gr.Textbox(label="Chunks de texto divididos", lines=20),
#    title="Text Splitter Demo",
#    description="Cole qualquer texto (incluindo LaTeX) e veja como ele é dividido em chunks usando RecursiveCharacterTextSplitter."
#)
#splitter_app.launch(server_port=5057)
# -- Suas interfaces de PDF e chatbot continuam funcionando como estão! --

# 3Lançando a interface de splitter 
#embedding_app = gr.Interface(
#    fn=embed_query_interface,
#    inputs=gr.Textbox(label="Digite a frase para embedar", value="How are you?"),
#    outputs=gr.Textbox(label="Embedding"),
#    title="Watsonx Embedding Demo",
#    description="Veja os primeiros 5 números do embedding para a frase fornecida."
#)

# Lança na porta 5058 (ou a que preferir)
#embedding_app.launch(server_port=5058)




#ex4
#vectordb_app = gr.Interface(
#    fn=vectordb_search_interface,
#    inputs=gr.Textbox(label="Consulta de busca", value="Política de fumo"),
#    outputs=gr.Textbox(label="Resultados encontrados"),
#    title="Chroma VectorDB Search Demo",
#    description="Carrega o new-Policies.txt, faz embedding e busca de similaridade para a consulta fornecida."
#)

# Lança na porta 5059 (ou a que preferir)
#vectordb_app.launch(server_port=5059)



# ex5
#retriever_app = gr.Interface(
#    fn=chroma_retriever_interface,
#    inputs=gr.Textbox(label="Consulta para recuperar", value="Email policy"),
#    outputs=gr.Textbox(label="Segmentos encontrados"),
#    title="ChromaDB Retriever Demo",
#    description="Carrega new-Policies.txt, indexa e recupera os 2 chunks mais relevantes para a consulta."
#)

# Lança a interface na porta 5060 (ajuste se precisar)
#retriever_app.launch(server_port=5060)